apiVersion: v1
kind: PersistentVolume
metadata:
  name: video-persistent-volume
spec:
  storageClassName: local-path
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /var/k8s/karate/video
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node
              operator: In
              values:
                - kubala