apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-deployment
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: frontend-deployment
          image: ghcr.io/jakbejk/karate-frontend:1.1.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: frontend-config-map
      restartPolicy: Always
      