apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: postgres-stateful-set
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432