apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-persistent-volume-claim
spec:
  volumeName: video-persistent-volume
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi