apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-stateful-set
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgres-persistent-volume-claim
      spec:
        storageClassName: local-path
        volumeName: postgres-persistent-volume
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          readinessProbe:
            tcpSocket:
              port: 5432
          livenessProbe:
            tcpSocket:
              port: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-volume-claim
          envFrom:
            - configMapRef:
                name: postgres-config-map