apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kubalaj-issuer
spec:
  acme:
    email: honzakubala@seznam.cz
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-issuer-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik